config/routes.rb
Projections::Application.routes.draw do

  get "users/new"
  get "projections/new"

  root to: 'pages#home'

  match '/about', to: 'pages#about'
  match '/help', to: 'pages#help'
  match '/feedback', to: 'pages#feedback'
  match '/contact', to: 'pages#contact'
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  resources :users
  resources :projections
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/film.rb
# == Schema Information
#
# Table name: films
#
#  projection_id :integer          not null, primary key
#  description   :text
#

class Film < ActiveRecord::Base
  inherits_from :projection

  attr_accessible :description
  validates_presence_of :description

end

app/models/painting.rb
# == Schema Information
#
# Table name: paintings
#
#  projection_id :integer          not null, primary key
#  description   :text
#

class Painting < ActiveRecord::Base
  inherits_from :projection

  attr_accessible :description
  validates_presence_of :description
end

app/models/projection.rb
# == Schema Information
#
# Table name: projections
#
#  id         :integer          not null, primary key
#  subtype    :string(255)      not null
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Projection < ActiveRecord::Base

  attr_accessible :name, :category, :description, :file
  belongs_to :user

  validates :name, :presence => true
  validates :user_id, :presence => true
  validates :description, presence: true, length: { maximum: 1000 }
  validates :file, presence: true, file_size: { maximum: 5.megabytes.to_i }
  mount_uploader :file, FileUploader
  default_scope order: 'projections.created_at DESC'
end

app/models/song.rb
# == Schema Information
#
# Table name: songs
#
#  projection_id :integer          not null, primary key
#  description   :text
#

class Song < ActiveRecord::Base
  inherits_from :projection

  attr_accessible :description
  validates_presence_of :description
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                    :integer          not null, primary key
#  name                  :string(255)
#  email                 :string(255)
#  password              :string(255)
#  password_confirmation :string(255)
#  admin                 :boolean
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_many :projections, dependent: :destroy
  has_secure_password

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

private

  def create_remember_token
  	self.remember_token = SecureRandom.urlsafe_base64
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def help
  end

  def contact
  end

  def feedback
  end
end

app/controllers/projections_controller.rb
class ProjectionsController < ApplicationController

  before_filter :signed_in_user, only: [:new, :create, :destroy]
  # before_filter :correct_user, only: [:new, :create, :destroy]

  def new
    @projection = Projection.new
  end

  def create
    @projection = current_user.projections.build(params[:projection])
    if @projection.save
      flash[:success] = "Projection submitted!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @projection = Projection.find(params[:id])
  end

  def index
    @projections = Projection.all
  end
 
  def destroy
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email].downcase)
    if user && user.authenticate(params[:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = "Invalid email/password combination"
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :signed_in_user, only: [:index, :edit, :update]
  before_filter :correct_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @projections = @user.projections.paginate(page: params[:page])
  end

  def index
    @users = User.paginate(page: 1)
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to Projections!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title)
    base_title = "Projections"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projections_helper.rb
module ProjectionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end


  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end  

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url	
  end

end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <span>
  Copyright Mark Willson 2013, All Rights Reserved
  </span>
    <ul>
      <li><%= link_to "About", '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar">
    <div class="container center" id="top">
      <%= link_to image_tag("logo_final.png", alt: "Projections"), root_path, id: "logo" %> 
      <ul class="nav nav-tabs" id="topnav">
        <% if signed_in? %>
          <li><%= link_to current_user.name, current_user, id: "toplink" %></li>
          <li><%= link_to "Settings", edit_user_path(current_user), id: "toplink" %></li>
          <li><%= link_to "Sign out", signout_path, id: "toplink", method: "delete" %></li>
        <% else %>
          <li><%= link_to "Sign in", signin_path, id: "toplink" %></li>
        <% end %>
      </ul>
    </div>
</header>

<header class="navbar" id="navigation">
  <div class="container center">
    <ul id="navlist" class="nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Browse Projections", projections_path %></li>
        <% if signed_in? %>
          <li><%= link_to "Browse by User", users_path %></li>
          <li><%= link_to "Create a Projection", new_projection_path %></li>
        <% end %>
        <li><%= link_to "Help", help_path %></li>
        <li><%= link_to "Feedback", feedback_path %></li>
    </ul>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html><html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag "/favicon.ico" %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="content">
    <div><br /><div>
    <div class="container center well">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
    <div><br /><div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/pages/about.html.erb
<h3>About</h3>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h3>Contact Us</h3>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/feedback.html.erb
<% provide(:title, 'Feedback') %>
<h2 class="center">Feedback</h2>

app/views/pages/help.html.erb
<% provide(:title, 'Help') %>
<h2 class="center">Help</h2>

<h4>If you've ever thought one of the following, then you are in the right place:</h4>
<ul>
  <li>Wouldn't it be cool to film a movie based on {insert artist name here}'s collective work?</li>
  <li>I'd like to draw a painting which could be used as cover art or sold as a band poster!</li>
  <li>I have a really neat song I've written, and I want {insert artist name here} to play it!</li> 
</ul>
<h4>When it comes to you, the 
  <span class="emphasis">user</span>, our focus is on two core principles: creator 
  <span class="emphasis">protection</span> and 
  <span class="emphasis">flexibility</span>.
</h4>
We want you to be able to maintain creative control over your work and still have plenty
of options when it comes to artist ownership. We believe you CAN have the best of both worlds.

[More about the features in place that exemplify these principles to come]

app/views/pages/home.html.erb
<h3>Here at Projections, we connect
  <span class="emphasis">your ideas</span> to the 
  <span class="emphasis">musicians</span> you love.
</h3><br />
<h3 class="emphasis"><a href=help class="emphasis">Learn more!</a></h3>
<h4>Artist? Get started <%= link_to "here", href: '#', id: "toplink" %>.</h4>

app/views/projections/_proj_form.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@projection) do |f| %>

      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :category %>
      <%= f.select( :category, [['Song','Song'],['Film','Film'],['Static Visual','Static']]) %>

      <%= f.label :description %>
      <%= f.text_area :description %>

      <%= f.label :file %>
      <%= f.file_field :file %>

      <%= f.submit "Create", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/projections/_projection.html.erb
<li>
  <%= link_to projection.name, projection_path(projection.id), class: "signin" %>
  <span class="timestamp">
    Posted <%= time_ago_in_words(projection.created_at) %> ago.
  </span>
</li>

app/views/projections/index.html.erb
<% provide(:title, 'All Projections') %>

<h2 class="center">All Projections</h2>
<div class = "center">
  <ol>
    <%= render @projections %>
  </ol>
</div>

app/views/projections/new.html.erb
<% provide(:title, 'New Projection') %>
<h2 class="center">New Projection</h2>

<%= render 'proj_form' %>

app/views/projections/show.html.erb
<% provide(:title, @projection.name) %>

<div class="center">
  <h2><%= @projection.name %></h2>
  <h3>Category: <%= @projection.category %></h3>
  <p class="center">
    <%= @projection.description %>
  </p>
</div>

app/views/shared/_commons_license.html.erb
<a rel="license" href="http://creativecommons.org/licenses/by-nd/3.0/deed.en_US">
  <img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-nd/3.0/80x15.png" />
</a><br />

<span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">
  "<%= @projection.name %>"
</span> 
  by 
<span xmlns:cc="http://creativecommons.org/ns#" property="cc:attributionName">
  "<%= @projection.author %>"
</span> 

  is licensed under a 
<a rel="license" href="http://creativecommons.org/licenses/by-nd/3.0/deed.en_US">
  Creative Commons Attribution-NoDerivs 3.0 Unported License
</a>.

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_proj_errors.html.erb
<% if @projection.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@projection.errors.count, "error") %>
    </div>
    <ul>
    <% @projection.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.text_field :email %>
  
  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation %>

app/views/users/_form_new.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages' %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.text_field :email %>
  
  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account", class: "btn btn-large" %>

<% end %>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<h2 class="center">Update your profile</h2>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'form', f:f %>
      <%= f.submit "Save changes", class: "btn btn-large" %>
    <% end %>
    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h2 class="center">All users</h2>

<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user, size: 52 %>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<div class="row">
  <div class="span6 offset3">
    <h2 class="center">Sign up</h2>
    <%= form_for(@user) do |f| %>
      <%= render 'form', f:f %>
      <%= f.submit "Create my account", class: "btn btn-large" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row"> 
 
  <aside class="span4">
    <section>
      <h2>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h2>
      <%= link_to "Create a Projection", new_projection_path %>
    </section>
  </aside>

  <div class="span8">
    <% if @user.projections.any? %>
      <h3>Projections (<%= @user.projections.count %>)</h3>
      <ol class="projections">
        <%= render @projections %>
      </ol>
      <%= will_paginate @projections %>
    <% end %>
  </div>

</div>